// import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`w-screen h-screen relative pt-16 bg-gray-100`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
